# NumPy : Introduction

**NumPy allows you to manipulate data in the form of an array.**

**Complete the missions below using NumPy.**

In [3]:
import numpy as np # Here we rename numpy as np, it's shorter, and everybody does that

# Mission 1 : Display the version of NumPy you are running (as each library, you can use np.__version__)
np.__version__

'1.23.5'

In [17]:
# Mission 2 : Create a NumPy array with a length of 3, that contains this 3 floats: 0.8, 0.6, 0.4
# Expected result: array([0.8, 0.6, 0.4])
my_na = np.array([0.8, 0.6, 0.4])
print(my_na)
my_na

[0.8 0.6 0.4]


array([0.8, 0.6, 0.4])

In [18]:
# Mission 3 : Create a function that uses the np.random.random() function to return an array with 10 random elements,
# all of which must be greater than 0.25 and less than 1.0

# Example of expected result: array([0.3897948 , 0.82850041, 0.5499838 , 0.81940137, 0.92175875, 0.89634373, 0.26821861, 0.72376496, 0.81098623, 0.28192741])

def random_array_generator():
    random_array = np.random.random(10)
    scale_array = 0.75 * random_array + 0.25
    return scale_array

result_array = random_array_generator()
print(result_array)
result_array

[0.62971774 0.80224568 0.35653519 0.52560632 0.39013602 0.48061417
 0.79294937 0.46039021 0.34470924 0.71885523]


array([0.62971774, 0.80224568, 0.35653519, 0.52560632, 0.39013602,
       0.48061417, 0.79294937, 0.46039021, 0.34470924, 0.71885523])

In [ ]:
# Mission 4 : What does the np.empty() method do? Don't just copy the documentation, explain in your own words here

# Alors de ce que j'ai compris, np.empty() permet de créer un tableau non initialisé (c.a.d que les éléments du tableau ne sont pas définit par nous même
# lors de sa création).  Elle n'initialise pas les éléments du tableau à une valeur particulière, de sorte que le contenu du tableau peut être n'importe quelle
# donnée aléatoire qui existe déjà dans l'emplacement mémoire assigné au tableau.
# la syntaxe de np.empty() est comme ça:  numpy.empty(shape, dtype=float, order='C')
#c'est important à savoir que les éléménts créer dans ce tableau vide se sont pas garanties d'être zero ou un value spécifique contrairement à np.zeros() ou np.ones().

In [12]:
# Mission 5 : Create an array filled with only zeros. You can choose the length of this array.
zero_array = np.zeros(9)
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [29]:
# Mission 6 : Create an array filled with 10 random integers.
random_integers_array = np.random.randint(1000, size=10)
print(random_integers_array)


[269 942 895 517 224 707 546  74 703 200]


In [16]:
# Mission 7 : Create an array that contains 50 values randomly selected only from these numbers: 0, 1, 2, 3, 4, 5, 6, 7.
random_array = np.random.choice([0, 1, 2, 3, 4, 5, 6, 7], size = 50)
print(random_array)

[6 5 1 2 6 7 1 5 1 0 5 5 4 4 5 7 2 1 0 1 4 5 0 1 0 4 5 1 1 7 2 7 5 0 1 5 2
 3 6 1 7 2 7 6 7 5 3 6 2 1]
