In [1]:
import numpy as np


Execute the cell below before starting the 1st mission.

In [2]:
array_1 = np.array([10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54,
       35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])

array_1

array([10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54,
       35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])

# Mission 1

Using Numpy, how many axes `array_1` has ?




In [13]:
num_axes = len(array_1.shape)
print(f"Le nombre d'axe est de: {num_axes}")

Le nombre d'axe est de: 1


Still using Numpy, how many dimensions `array_1` has?

In [14]:
num_dim = array_1.ndim
print(f"le nombre de dimension de array_1 est de: {num_dim}")

le nombre de dimension de array_1 est de: 1


Display the first element of `array_1`

In [15]:
first_element = array_1[0]
print(first_element)

10


# Mission 2

Modify, using a `numpy` method, the `array_1` object to be an object that has two axes, including 1 row and 32 columns.  
Save it under the variable `array_2`.

In [16]:
array_2 = np.reshape(array_1, (1, 32))
print(array_1)
print(array_2)

[10 40 45  5 66 91 43 75 40 28 55 45 31 71 67 54 54 35 64 27 12 93 17 91
 50 57 74 61 86 20 36 35]
[[10 40 45  5 66 91 43 75 40 28 55 45 31 71 67 54 54 35 64 27 12 93 17 91
  50 57 74 61 86 20 36 35]]


Now, modify `array_1` into an object that has 32 rows and only 1 column.  
Save it under the variable `array_3`.

In [36]:
array_3 = np.reshape(array_1, (32, 1))
print(array_1)
print(array_3)

[10 40 45  5 66 91 43 75 40 28 55 45 31 71 67 54 54 35 64 27 12 93 17 91
 50 57 74 61 86 20 36 35]
[[10]
 [40]
 [45]
 [ 5]
 [66]
 [91]
 [43]
 [75]
 [40]
 [28]
 [55]
 [45]
 [31]
 [71]
 [67]
 [54]
 [54]
 [35]
 [64]
 [27]
 [12]
 [93]
 [17]
 [91]
 [50]
 [57]
 [74]
 [61]
 [86]
 [20]
 [36]
 [35]]


Access the first element of `array_2`, then of `array_3`.  
What do you notice?  
Why ?

In [20]:
first_element_a2 = array_2[0, 0]
first_element_a3 = array_3[0, 0]

print(first_element_a2)
print(first_element_a3)
# On remarque que c'est le même élément que dans array_1 ce qui veut dire que le reshape ne modifie pas les ordres des éléments.
# Cependant on remarque que contrairement à l'excercie précédent quand on cherchait le premier element de array_1 nous avions juste besoin de [0]
# Alors que pour array_2 et 3 nous devons faire [0,0] car la notation d'indices et différente entre tableau unidimensionel et multidimensionel

10
10


# Mission 3

Access the value that is at index 3 of array `array_2`.  
Do it with Numpy way, then with Python way.

In [22]:
#Numpy Way
value_index_3_numpy = array_2[0, 3]
print("Value at index 3 of array_2 with Numpy:",value_index_3_numpy)

#Python Way
value_index_3_python = array_2[0][3]
print("Value at index 3 of array_2 with Python",value_index_3_python)

Value at index 3 of array_2 with Numpy: 5
Value at index 3 of array_2 with Python 5


Access the value which is at index 3 of array `array_3` in Numpy.

In [23]:
value_index_3 = array_3[0, 3]
print(value_index_3)

5


# Mission 4

Reshape `array_1` to be a 4-row, 8-column array,
rather than a 32-element vector.  
Save your array under the variable `array_4`.

In [24]:
array_4 = np.reshape(array_1, (4, 8))
print("Original array_1:")
print(array_1)
print("\nReshaped array_4:")
print(array_4)







Original array_1:
[10 40 45  5 66 91 43 75 40 28 55 45 31 71 67 54 54 35 64 27 12 93 17 91
 50 57 74 61 86 20 36 35]

Reshaped array_4:
[[10 40 45  5 66 91 43 75]
 [40 28 55 45 31 71 67 54]
 [54 35 64 27 12 93 17 91]
 [50 57 74 61 86 20 36 35]]


Access for each row, the values ​​of the columns which have the index 1 to 2 included.

In [25]:
array_4 = np.array([[10, 40, 45, 5, 66, 91, 43, 75],
                    [40, 28, 55, 45, 31, 71, 67, 54],
                    [54, 35, 64, 27, 12, 93, 17, 91],
                    [50, 57, 74, 61, 86, 20, 36, 35]])
values_columns_1_to_2 = array_4[:, 1:3]
print("Values for each row from columns with indices 1 to 2:")
print(values_columns_1_to_2)

Values for each row from columns with indices 1 to 2:
[[40 45]
 [28 55]
 [35 64]
 [57 74]]


Access for rows at position 1 and 2 inclusive, the values ​​of all columns.

In [26]:
values_rows_1_to_2 = array_4[1:3, :]
print("Values for rows at positions 1 and 2 for all columns:")
print(values_rows_1_to_2)

Values for rows at positions 1 and 2 for all columns:
[[40 28 55 45 31 71 67 54]
 [54 35 64 27 12 93 17 91]]


Access for the rows which have the index 2 to 3 inclusive, to the values ​​of the columns which have the index 3 to 5 inclusive.

In [27]:
values_rows_2_to_3_columns_3_to_5 = array_4[2:4, 3:6]
print("Values for rows with indices 2 to 3 and columns with indices 3 to 5:")
print(values_rows_2_to_3_columns_3_to_5)

Values for rows with indices 2 to 3 and columns with indices 3 to 5:
[[27 12 93]
 [61 86 20]]


Select the first column, as well as the columns whose index is a multiple of 2.

In [28]:
selected_columns = array_4[:, ::2]
print(selected_columns)

[[10 45 66 43]
 [40 55 31 67]
 [54 64 12 17]
 [50 74 86 36]]


Select columns whose index is odd.

In [29]:
selected_columns_odd = array_4[:, 1::2]
print(selected_columns_odd)

[[40  5 91 75]
 [28 45 71 54]
 [35 27 93 91]
 [57 61 20 35]]


# Mission 5

Reshape your `array_1` vector into a 3-dimensional array.
Your 3-dimensional array should have 2 matrices, each of which has 4 rows and 4 columns.
Save your array under the variable `array_5`.

In [30]:
array_1 = np.array([10, 40, 45, 5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54, 35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])


array_5 = np.reshape(array_1, (2, 4, 4))


print("Reshaped array_5:")
print(array_5)

Reshaped array_5:
[[[10 40 45  5]
  [66 91 43 75]
  [40 28 55 45]
  [31 71 67 54]]

 [[54 35 64 27]
  [12 93 17 91]
  [50 57 74 61]
  [86 20 36 35]]]


Use the .shape attribute to observe the number of axes for `array_5`.

In [31]:
num_axes_array_5 = len(array_5.shape)
print(f'the numbers of axes for array_5 is: {num_axes_array_5}')


the numbers of axes for array_5 is: 3


Select all values ​​from the first matrix.

In [32]:
array_5 = np.reshape(np.array([10, 40, 45, 5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54, 35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35]), (2, 4, 4))
values_first_matrix = array_5[0, :, :]

print("All values from the first matrix:")
print(values_first_matrix)

All values from the first matrix:
[[10 40 45  5]
 [66 91 43 75]
 [40 28 55 45]
 [31 71 67 54]]


Access for both matrices,
to the values ​​corresponding to the rows at index 1 and to the columns that have positions 3 and 4.

In [33]:
values_both_matrices_rows1_columns3to4 = array_5[:, 1, 2:4]
print("Values for both matrices, rows at index 1 and columns at positions 3 and 4:")
print(values_both_matrices_rows1_columns3to4)

Values for both matrices, rows at index 1 and columns at positions 3 and 4:
[[43 75]
 [17 91]]


Access row values ​​at positions 2 to 3,
columns at indexes 1 to 3 included for the second matrix only.

In [34]:
values_second_matrix_rows2to3_columns1to3 = array_5[1, 1:3, 1:4]
print("Values for the second matrix, rows at positions 2 to 3 and columns at indexes 1 to 3:")
print(values_second_matrix_rows2to3_columns1to3)

Values for the second matrix, rows at positions 2 to 3 and columns at indexes 1 to 3:
[[93 17 91]
 [57 74 61]]



Reshape `array_5` so that we have 8 rows and 4 columns.

In [35]:
array_5_reshaped = np.reshape(array_5, (8, 4))
print("Original array_5:")
print(array_5)
print("\nReshaped array_5:")
print(array_5_reshaped)

Original array_5:
[[[10 40 45  5]
  [66 91 43 75]
  [40 28 55 45]
  [31 71 67 54]]

 [[54 35 64 27]
  [12 93 17 91]
  [50 57 74 61]
  [86 20 36 35]]]

Reshaped array_5:
[[10 40 45  5]
 [66 91 43 75]
 [40 28 55 45]
 [31 71 67 54]
 [54 35 64 27]
 [12 93 17 91]
 [50 57 74 61]
 [86 20 36 35]]
